- name: データベースを作成する
  mysql_db:
    name: "{{ item }}"
    state: present
    encoding: utf8mb4
  with_items:
    - "{{ mysql_app_database_name }}"
    - "{{ mysql_test_database_name }}"

- name: ユーザーを作成する
  mysql_user:
    name: "{{ mysql_user_name }}"
    password: "{{ mysql_user_password }}"
    priv: '*.*:ALL,GRANT'
    state: present

- name: MySQLの設定ファイルをデプロイする
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf