- name: http接続をを許可する
  firewalld:
    service: http
    state: enabled
    permanent: true
    immediate: true

- name: 80番ポートを許可する
  firewalld:
    port: 80/tcp
    state: enabled
    permanent: true
    immediate: true

- name: 443番ポートを許可する
  firewalld:
    port: 443/tcp
    state: enabled
    permanent: true
    immediate: true